# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: janhoon <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/05/22 11:11:37 by janhoon           #+#    #+#              #
#    Updated: 2017/05/22 11:11:44 by janhoon          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

megaphone:
	clang++ -Wall -Wextra -Werror -o megaphone megaphone.cpp -I ./

clean:
	rm megaphone

re:
	make clean 
	make megaphone